version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    platform: linux/amd64
    image: pogodingleb/backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    platform: linux/amd64
    container_name: frontend
    image: pogodingleb/frontend:1
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    platform: linux/amd64
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
volumes:
  db_data:
  static_value:
  media_value: