# Generated by Django 4.2.1 on 2023-05-13 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Favorite',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='\nrecipes_subscribe recipe is favorite alredy\n',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='\nrecipes_favorite recipe is favorite alredy\n'),
        ),
    ]
